

# Database Configuration
server:
  port: 1000

spring:
  datasource:
    url: jdbc:mysql://localhost:3306/PAYMENT_INFO
    username: root
    password: Ryzen@12
    driver-class-name : com.mysql.cj.jdbc.Driver

  main:
    web-application-type=none:
    allow-circular-references: true

  jpa:
    properties:
      hibernate:
        dialect: org.hibernate.dialect.MySQL8Dialect
    hibernate:
      ddl-auto: update
    show-sql: true


